# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfviewerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpdf',
            name='nb_pages',
            field=models.IntegerField(default=0),
        ),
    ]
